ifood:
  open-weather:
    base-url: https://api.openweathermap.org/data/2.5/weather?appid={appid}&units={units}&q={q}&lat={lat}&lon={lon}
    units: metric
  spotify:
    base-url: https://api.spotify.com
    access-token-url: https://accounts.spotify.com/api/token

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_empty